# Introduction to DataFrames

- A dataframe represents a tabular data (table)
- Contains rows and columns
- By default, rows are referred by index (0 to n-1)
- And columns are also referred by their index
- Rows are at axis=0 (x-axis), and columns are at axis=1 (y-axis)

In [2]:
# imports
import numpy as np
import pandas as pd

In [3]:
data = {
    'city':['hyd', 'del', 'mum', 'che', 'kol'],
    'state':['telangana', 'delhi', 'maharastra', 'tamilnadu', 'west bengal'],
    'population':[15000000, 18000000, 14000000, 16000000, 12000000]
}

In [4]:
pd.DataFrame(data)

  city        state  population
0  hyd    telangana    15000000
1  del        delhi    18000000
2  mum   maharastra    14000000
3  che    tamilnadu    16000000
4  kol  west bengal    12000000

In [5]:
customer_visits = np.random.randint(10, 25, (3, 5))
customer_visits

array([[10, 17, 21, 22, 24],
       [20, 15, 13, 24, 14],
       [21, 17, 13, 24, 12]])

In [6]:
pd.DataFrame(customer_visits)

    0   1   2   3   4
0  10  17  21  22  24
1  20  15  13  24  14
2  21  17  13  24  12

In [7]:
pd.DataFrame(customer_visits, index=['Morning', 'Afternoon', 'Evening'])

            0   1   2   3   4
Morning    10  17  21  22  24
Afternoon  20  15  13  24  14
Evening    21  17  13  24  12

In [8]:
pd.DataFrame(customer_visits, 
             index=['Morning', 'Afternoon', 'Evening'],
            columns=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])

           Mon  Tue  Wed  Thu  Fri
Morning     10   17   21   22   24
Afternoon   20   15   13   24   14
Evening     21   17   13   24   12

## Loading files

```python
# pandas functions to load files
read_csv() # for csv files
read_json() # for json files
read_excel() # for excel files
read_sql_query() # for sql queries
```

In [9]:
pd.read_csv("./files/movies.csv")

     Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

In [10]:
pd.read_csv("./files/movies.csv", index_col="Title")

                              Rank           Studio       Gross  Year
Title
Avengers: Endgame                1      Buena Vista  $2,796.30   2019
Avatar                           2              Fox  $2,789.70   2009
Titanic                          3        Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4      Buena Vista  $2,068.20   2015
Avengers: Infinity War           5      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
Yogi Bear                      778  Warner Brothers    $201.60   2010
Garfield: The Movie            779              Fox    $200.80   2004
Cats & Dogs                    780  Warner Brothers    $200.70   2001
The Hunt for Red October       781        Paramount    $200.50   1990
Valkyrie                       782              MGM    $200.30   2008

[782 rows x 4 columns]

In [11]:
movies = pd.read_csv("./files/movies.csv")
movies

     Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

In [12]:
len(movies)  # find the number of rows

782

In [13]:
# head(n) - to display first n rows, by default n value is 5
movies.head()

   Rank                         Title       Studio       Gross  Year
0     1             Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2                        Avatar          Fox  $2,789.70   2009
2     3                       Titanic    Paramount  $2,187.50   1997
3     4  Star Wars: The Force Awakens  Buena Vista  $2,068.20   2015
4     5        Avengers: Infinity War  Buena Vista  $2,048.40   2018

In [14]:
movies.head(8)  # shows first 8 rows

   Rank                         Title       Studio       Gross  Year
0     1             Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2                        Avatar          Fox  $2,789.70   2009
2     3                       Titanic    Paramount  $2,187.50   1997
3     4  Star Wars: The Force Awakens  Buena Vista  $2,068.20   2015
4     5        Avengers: Infinity War  Buena Vista  $2,048.40   2018
5     6                Jurassic World    Universal  $1,671.70   2015
6     7         Marvel's The Avengers  Buena Vista  $1,518.80   2012
7     8                     Furious 7    Universal  $1,516.00   2015

In [15]:
# tail(n) - display the last n-rows, by default, n value is 5
movies.tail(3)

     Rank                     Title           Studio     Gross  Year
779   780               Cats & Dogs  Warner Brothers  $200.70   2001
780   781  The Hunt for Red October        Paramount  $200.50   1990
781   782                  Valkyrie              MGM  $200.30   2008

In [16]:
# To know the shape use the `shape` attribute
movies.shape

(782, 5)

In [17]:
# To know the total number values use `size` attribute
movies.size

3910

In [19]:
movies.head(5)

   Rank                         Title       Studio       Gross  Year
0     1             Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2                        Avatar          Fox  $2,789.70   2009
2     3                       Titanic    Paramount  $2,187.50   1997
3     4  Star Wars: The Force Awakens  Buena Vista  $2,068.20   2015
4     5        Avengers: Infinity War  Buena Vista  $2,048.40   2018

In [20]:
# dtypes - dtypes attribute to know the datatypes of each column in the DataFrame
movies.dtypes

Rank       int64
Title     object
Studio    object
Gross     object
Year       int64
dtype: object

In [21]:
# info() method - to inspect the DataFrame
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rank    782 non-null    int64
 1   Title   782 non-null    object
 2   Studio  782 non-null    object
 3   Gross   782 non-null    object
 4   Year    782 non-null    int64
dtypes: int64(2), object(3)
memory usage: 30.7+ KB

In [22]:
# describe() - for descriptive statistics
# describe works only on numeric columns
movies.describe()

             Rank         Year
count  782.000000   782.000000
mean   391.500000  2006.620205
std    225.888247    10.026227
min      1.000000  1939.000000
25%    196.250000  2001.000000
50%    391.500000  2009.000000
75%    586.750000  2014.000000
max    782.000000  2019.000000

In [23]:
# similar to transposing a matrix
movies.transpose()

,0,1,2,3,4,5,6,7,8,9,...,772,773,774,775,776,777,778,779,780,781
Rank,1,2,3,4,5,6,7,8,9,10,...,773,774,775,776,777,778,779,780,781,782
Title,Avengers: Endgame,Avatar,Titanic,Star Wars: The Force Awakens,Avengers: Infinity War,Jurassic World,Marvel's The Avengers,Furious 7,Avengers: Age of Ultron,Black Panther,...,Fun with Dick and Jane,Teenage Mutant Ninja Turtles,Kindergarten Cop,Straight Outta Compton,21 Jump Street,Yogi Bear,Garfield: The Movie,Cats & Dogs,The Hunt for Red October,Valkyrie
Studio,Buena Vista,Fox,Paramount,Buena Vista,Buena Vista,Universal,Buena Vista,Universal,Buena Vista,Buena Vista,...,Sony,New Line,Universal,Universal,Sony,Warner Brothers,Fox,Warner Brothers,Paramount,MGM
Gross,"$2,796.30","$2,789.70","$2,187.50","$2,068.20","$2,048.40","$1,671.70","$1,518.80","$1,516.00","$1,405.40","$1,346.90",...,$202.00,$202.00,$202.00,$201.60,$201.60,$201.60,$200.80,$200.70,$200.50,$200.30
Year,2019,2009,1997,2015,2018,2015,2012,2015,2015,2018,...,2005,1990,1990,2015,2012,2010,2004,2001,1990,2008

In [24]:
# T for transpose
movies.T

,0,1,2,3,4,5,6,7,8,9,...,772,773,774,775,776,777,778,779,780,781
Rank,1,2,3,4,5,6,7,8,9,10,...,773,774,775,776,777,778,779,780,781,782
Title,Avengers: Endgame,Avatar,Titanic,Star Wars: The Force Awakens,Avengers: Infinity War,Jurassic World,Marvel's The Avengers,Furious 7,Avengers: Age of Ultron,Black Panther,...,Fun with Dick and Jane,Teenage Mutant Ninja Turtles,Kindergarten Cop,Straight Outta Compton,21 Jump Street,Yogi Bear,Garfield: The Movie,Cats & Dogs,The Hunt for Red October,Valkyrie
Studio,Buena Vista,Fox,Paramount,Buena Vista,Buena Vista,Universal,Buena Vista,Universal,Buena Vista,Buena Vista,...,Sony,New Line,Universal,Universal,Sony,Warner Brothers,Fox,Warner Brothers,Paramount,MGM
Gross,"$2,796.30","$2,789.70","$2,187.50","$2,068.20","$2,048.40","$1,671.70","$1,518.80","$1,516.00","$1,405.40","$1,346.90",...,$202.00,$202.00,$202.00,$201.60,$201.60,$201.60,$200.80,$200.70,$200.50,$200.30
Year,2019,2009,1997,2015,2018,2015,2012,2015,2015,2018,...,2005,1990,1990,2015,2012,2010,2004,2001,1990,2008

In [25]:
movies.head(3)

   Rank              Title       Studio       Gross  Year
0     1  Avengers: Endgame  Buena Vista  $2,796.30   2019
1     2             Avatar          Fox  $2,789.70   2009
2     3            Titanic    Paramount  $2,187.50   1997

In [26]:
type(movies)

pandas.core.frame.DataFrame

In [27]:
# accessing a column using index operator
movies["Gross"]

0      $2,796.30
1      $2,789.70
2      $2,187.50
3      $2,068.20
4      $2,048.40
          ...
777      $201.60
778      $200.80
779      $200.70
780      $200.50
781      $200.30
Name: Gross, Length: 782, dtype: object

In [28]:
type(movies["Gross"])

pandas.core.series.Series

In [29]:
# use dot (.) operator to access a single column
movies.Gross

0      $2,796.30
1      $2,789.70
2      $2,187.50
3      $2,068.20
4      $2,048.40
          ...
777      $201.60
778      $200.80
779      $200.70
780      $200.50
781      $200.30
Name: Gross, Length: 782, dtype: object

In [31]:
type(movies.Gross)

pandas.core.series.Series

In [32]:
# extracting two columns or more creates a DataFrame
movies[["Title", "Gross"]]

                            Title       Gross
0               Avengers: Endgame  $2,796.30
1                          Avatar  $2,789.70
2                         Titanic  $2,187.50
3    Star Wars: The Force Awakens  $2,068.20
4          Avengers: Infinity War  $2,048.40
..                            ...         ...
777                     Yogi Bear    $201.60
778           Garfield: The Movie    $200.80
779                   Cats & Dogs    $200.70
780      The Hunt for Red October    $200.50
781                      Valkyrie    $200.30

[782 rows x 2 columns]

In [33]:
type(movies[["Title", "Gross"]])

pandas.core.frame.DataFrame

In [36]:
# one column as dataFrmae
type(movies[["Gross"]])

pandas.core.frame.DataFrame

In [38]:
movies[["Gross"]]

          Gross
0    $2,796.30
1    $2,789.70
2    $2,187.50
3    $2,068.20
4    $2,048.40
..          ...
777    $201.60
778    $200.80
779    $200.70
780    $200.50
781    $200.30

[782 rows x 1 columns]

In [39]:
# fixing the Gross column

In [51]:
movies["Gross"].str.replace("$", "").str.replace(",","").str.strip().astype('float')

0      2796.3
1      2789.7
2      2187.5
3      2068.2
4      2048.4
        ...
777     201.6
778     200.8
779     200.7
780     200.5
781     200.3
Name: Gross, Length: 782, dtype: float64

In [52]:
# creates a new column name 'Gross_New'
movies["Gross_New"] = movies["Gross"].str.replace("$", "").str.replace(",","").str.strip().astype('float')

In [54]:
movies[["Gross", "Gross_New"]]

          Gross  Gross_New
0    $2,796.30      2796.3
1    $2,789.70      2789.7
2    $2,187.50      2187.5
3    $2,068.20      2068.2
4    $2,048.40      2048.4
..          ...        ...
777    $201.60       201.6
778    $200.80       200.8
779    $200.70       200.7
780    $200.50       200.5
781    $200.30       200.3

[782 rows x 2 columns]

In [58]:
movies = movies.rename(columns={"Gross_New":"Gross_Millions"})

In [59]:
movies

,Rank,Title,Studio,Gross,Year,Gross_Millions
0,1,Avengers: Endgame,Buena Vista,"$2,796.30",2019,2796.3
1,2,Avatar,Fox,"$2,789.70",2009,2789.7
2,3,Titanic,Paramount,"$2,187.50",1997,2187.5
3,4,Star Wars: The Force Awakens,Buena Vista,"$2,068.20",2015,2068.2
4,5,Avengers: Infinity War,Buena Vista,"$2,048.40",2018,2048.4
...,...,...,...,...,...,...
777,778,Yogi Bear,Warner Brothers,$201.60,2010,201.6
778,779,Garfield: The Movie,Fox,$200.80,2004,200.8
779,780,Cats & Dogs,Warner Brothers,$200.70,2001,200.7
780,781,The Hunt for Red October,Paramount,$200.50,1990,200.5
781,782,Valkyrie,MGM,$200.30,2008,200.3