# Introduction to DataFrames

- A dataframe represents a tabular data (table)
- Contains rows and columns
- By default, rows are referred by index (0 to n-1)
- And columns are also referred by their index
- Rows are at axis=0 (x-axis), and columns are at axis=1 (y-axis)

In [1]:
# imports
import numpy as np
import pandas as pd

In [2]:
data = {
    'city':['hyd', 'del', 'mum', 'che', 'kol'],
    'state':['telangana', 'delhi', 'maharastra', 'tamilnadu', 'west bengal'],
    'population':[15000000, 18000000, 14000000, 16000000, 12000000]
}

In [3]:
pd.DataFrame(data)

  city        state  population
0  hyd    telangana    15000000
1  del        delhi    18000000
2  mum   maharastra    14000000
3  che    tamilnadu    16000000
4  kol  west bengal    12000000

In [4]:
customer_visits = np.random.randint(10, 25, (3, 5))
customer_visits

array([[24, 24, 11, 20, 14],
       [16, 10, 16, 13, 20],
       [17, 11, 16, 20, 14]])

In [5]:
pd.DataFrame(customer_visits)

    0   1   2   3   4
0  24  24  11  20  14
1  16  10  16  13  20
2  17  11  16  20  14

In [6]:
pd.DataFrame(customer_visits, index=['Morning', 'Afternoon', 'Evening'])

            0   1   2   3   4
Morning    24  24  11  20  14
Afternoon  16  10  16  13  20
Evening    17  11  16  20  14

In [7]:
pd.DataFrame(customer_visits, 
             index=['Morning', 'Afternoon', 'Evening'],
            columns=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])

           Mon  Tue  Wed  Thu  Fri
Morning     24   24   11   20   14
Afternoon   16   10   16   13   20
Evening     17   11   16   20   14

## Loading files

```python
# pandas functions to load files
read_csv() # for csv files
read_json() # for json files
read_excel() # for excel files
read_sql_query() # for sql queries
```

In [9]:
pd.read_csv("./files/movies.csv")

     Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

In [10]:
pd.read_csv("./files/movies.csv", index_col="Title")

                              Rank           Studio       Gross  Year
Title
Avengers: Endgame                1      Buena Vista  $2,796.30   2019
Avatar                           2              Fox  $2,789.70   2009
Titanic                          3        Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4      Buena Vista  $2,068.20   2015
Avengers: Infinity War           5      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
Yogi Bear                      778  Warner Brothers    $201.60   2010
Garfield: The Movie            779              Fox    $200.80   2004
Cats & Dogs                    780  Warner Brothers    $200.70   2001
The Hunt for Red October       781        Paramount    $200.50   1990
Valkyrie                       782              MGM    $200.30   2008

[782 rows x 4 columns]

In [11]:
movies = pd.read_csv("./files/movies.csv")
movies

     Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

In [12]:
len(movies)

782