# WORKING WITH DATAFRAMES

In [11]:
# IMPORTS
import numpy as np
import pandas as pd

In [17]:
days_of_war = pd.read_csv("revolutionary_war.csv")
days_of_war

                                Battle  Start Date          State
0                         Powder Alarm    9/1/1774  Massachusetts
1    Storming of Fort William and Mary  12/14/1774  New Hampshire
2     Battles of Lexington and Concord   4/19/1775  Massachusetts
3                      Siege of Boston   4/19/1775  Massachusetts
4                   Gunpowder Incident   4/20/1775       Virginia
..                                 ...         ...            ...
227                Siege of Fort Henry   9/11/1782       Virginia
228         Grand Assault on Gibraltar   9/13/1782            NaN
229          Action of 18 October 1782  10/18/1782            NaN
230          Action of 6 December 1782   12/6/1782            NaN
231          Action of 22 January 1783   1/22/1783       Virginia

[232 rows x 3 columns]

In [18]:
days_of_war.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Battle      232 non-null    object
 1   Start Date  228 non-null    object
 2   State       162 non-null    object
dtypes: object(3)
memory usage: 5.6+ KB

In [19]:
# extracting data from the dates from
days_of_war = pd.read_csv("revolutionary_war.csv", parse_dates=["Start Date"])
days_of_war

                                Battle Start Date          State
0                         Powder Alarm 1774-09-01  Massachusetts
1    Storming of Fort William and Mary 1774-12-14  New Hampshire
2     Battles of Lexington and Concord 1775-04-19  Massachusetts
3                      Siege of Boston 1775-04-19  Massachusetts
4                   Gunpowder Incident 1775-04-20       Virginia
..                                 ...        ...            ...
227                Siege of Fort Henry 1782-09-11       Virginia
228         Grand Assault on Gibraltar 1782-09-13            NaN
229          Action of 18 October 1782 1782-10-18            NaN
230          Action of 6 December 1782 1782-12-06            NaN
231          Action of 22 January 1783 1783-01-22       Virginia

[232 rows x 3 columns]

In [20]:
days_of_war.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Battle      232 non-null    object
 1   Start Date  228 non-null    datetime64[ns]
 2   State       162 non-null    object
dtypes: datetime64[ns](1), object(2)
memory usage: 5.6+ KB

In [21]:
days_of_war = pd.read_csv(
    "revolutionary_war.csv",
    parse_dates=["Start Date"],
    usecols=["Start Date"]
)
days_of_war

    Start Date
0   1774-09-01
1   1774-12-14
2   1775-04-19
3   1775-04-19
4   1775-04-20
..         ...
227 1782-09-11
228 1782-09-13
229 1782-10-18
230 1782-12-06
231 1783-01-22

[232 rows x 1 columns]

In [22]:
type(days_of_war)

pandas.core.frame.DataFrame

In [28]:
days_of_war = pd.read_csv(
    "revolutionary_war.csv",
    parse_dates=["Start Date"],    # converting the column to datetime
    usecols=["Start Date"],        # choose the columns to be in a dataframe
).squeeze()                        # if the dataframe has one column it can be squeezed to a series
days_of_war

0     1774-09-01
1     1774-12-14
2     1775-04-19
3     1775-04-19
4     1775-04-20
         ...
227   1782-09-11
228   1782-09-13
229   1782-10-18
230   1782-12-06
231   1783-01-22
Name: Start Date, Length: 232, dtype: datetime64[ns]

In [29]:
days_of_war.info()

<class 'pandas.core.series.Series'>
RangeIndex: 232 entries, 0 to 231
Series name: Start Date
Non-Null Count  Dtype
--------------  -----
228 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.9 KB

In [37]:
days_of_war = days_of_war.dropna() # dropna() to drop the missing values

In [39]:
from datetime import datetime
def day_of_week(date):
    return date.strftime("%A")

# days_of_war.dropna().apply(day_of_week)
days_of_war.apply(day_of_week) # use the apply() method to apply a UDF on a Series

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object

In [41]:
days_of_war = days_of_war.dropna().apply(day_of_week)
days_of_war

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object

In [42]:
days_of_war.value_counts()   # count the occurances of each value in the SEries

Start Date
Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: count, dtype: int64

### WORKING WITH NBA DATA

In [45]:
nba = pd.read_csv("nba.csv")
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    object
 4   Salary    450 non-null    int64
dtypes: int64(1), object(4)
memory usage: 17.7+ KB

In [46]:
nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])
nba

C:\Users\singa\AppData\Local\Temp\ipykernel_10292\2377021467.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [48]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB