# WORKING WITH DATAFRAMES

In [1]:
# IMPORTS
import numpy as np
import pandas as pd

In [2]:
days_of_war = pd.read_csv("revolutionary_war.csv")
days_of_war

                                Battle  Start Date          State
0                         Powder Alarm    9/1/1774  Massachusetts
1    Storming of Fort William and Mary  12/14/1774  New Hampshire
2     Battles of Lexington and Concord   4/19/1775  Massachusetts
3                      Siege of Boston   4/19/1775  Massachusetts
4                   Gunpowder Incident   4/20/1775       Virginia
..                                 ...         ...            ...
227                Siege of Fort Henry   9/11/1782       Virginia
228         Grand Assault on Gibraltar   9/13/1782            NaN
229          Action of 18 October 1782  10/18/1782            NaN
230          Action of 6 December 1782   12/6/1782            NaN
231          Action of 22 January 1783   1/22/1783       Virginia

[232 rows x 3 columns]

In [3]:
days_of_war.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Battle      232 non-null    object
 1   Start Date  228 non-null    object
 2   State       162 non-null    object
dtypes: object(3)
memory usage: 5.6+ KB

In [4]:
# extracting data from the dates from
days_of_war = pd.read_csv("revolutionary_war.csv", parse_dates=["Start Date"])
days_of_war

                                Battle Start Date          State
0                         Powder Alarm 1774-09-01  Massachusetts
1    Storming of Fort William and Mary 1774-12-14  New Hampshire
2     Battles of Lexington and Concord 1775-04-19  Massachusetts
3                      Siege of Boston 1775-04-19  Massachusetts
4                   Gunpowder Incident 1775-04-20       Virginia
..                                 ...        ...            ...
227                Siege of Fort Henry 1782-09-11       Virginia
228         Grand Assault on Gibraltar 1782-09-13            NaN
229          Action of 18 October 1782 1782-10-18            NaN
230          Action of 6 December 1782 1782-12-06            NaN
231          Action of 22 January 1783 1783-01-22       Virginia

[232 rows x 3 columns]

In [5]:
days_of_war.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Battle      232 non-null    object
 1   Start Date  228 non-null    datetime64[ns]
 2   State       162 non-null    object
dtypes: datetime64[ns](1), object(2)
memory usage: 5.6+ KB

In [6]:
days_of_war = pd.read_csv(
    "revolutionary_war.csv",
    parse_dates=["Start Date"],
    usecols=["Start Date"]
)
days_of_war

    Start Date
0   1774-09-01
1   1774-12-14
2   1775-04-19
3   1775-04-19
4   1775-04-20
..         ...
227 1782-09-11
228 1782-09-13
229 1782-10-18
230 1782-12-06
231 1783-01-22

[232 rows x 1 columns]

In [7]:
type(days_of_war)

pandas.core.frame.DataFrame

In [8]:
days_of_war = pd.read_csv(
    "revolutionary_war.csv",
    parse_dates=["Start Date"],    # converting the column to datetime
    usecols=["Start Date"],        # choose the columns to be in a dataframe
).squeeze()                        # if the dataframe has one column it can be squeezed to a series
days_of_war

0     1774-09-01
1     1774-12-14
2     1775-04-19
3     1775-04-19
4     1775-04-20
         ...
227   1782-09-11
228   1782-09-13
229   1782-10-18
230   1782-12-06
231   1783-01-22
Name: Start Date, Length: 232, dtype: datetime64[ns]

In [9]:
days_of_war.info()

<class 'pandas.core.series.Series'>
RangeIndex: 232 entries, 0 to 231
Series name: Start Date
Non-Null Count  Dtype
--------------  -----
228 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.9 KB

In [10]:
days_of_war = days_of_war.dropna() # dropna() to drop the missing values

In [11]:
from datetime import datetime
def day_of_week(date):
    return date.strftime("%A")

# days_of_war.dropna().apply(day_of_week)
days_of_war.apply(day_of_week) # use the apply() method to apply a UDF on a Series

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object

In [12]:
days_of_war = days_of_war.dropna().apply(day_of_week)
days_of_war

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object

In [13]:
days_of_war.value_counts()   # count the occurances of each value in the SEries

Start Date
Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: count, dtype: int64

### WORKING WITH NBA DATA

In [14]:
nba = pd.read_csv("nba.csv")
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    object
 4   Salary    450 non-null    int64
dtypes: int64(1), object(4)
memory usage: 17.7+ KB

In [15]:
nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])
nba

C:\Users\singa\AppData\Local\Temp\ipykernel_13252\2377021467.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [16]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

#### More methods on a dataframe

In [17]:
nba.sample(3)

               Name                    Team Position   Birthday   Salary
232      Jeff Green               Utah Jazz       PF 1986-08-28  2564753
286  Treveon Graham  Minnesota Timberwolves       SG 1993-10-28  1645357
391       Raul Neto      Philadelphia 76ers       PG 1992-05-19  1737145

In [18]:
# nlargest() method - get rows based by fitering upto nth largest values
nba.nlargest(n=10, columns="Salary")

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000
264       James Harden        Houston Rockets       PG 1989-08-26  38199000
408       LeBron James     Los Angeles Lakers       PF 1984-12-30  37436858
95        Kevin Durant          Brooklyn Nets       PF 1988-09-29  37199000
317      Blake Griffin        Detroit Pistons       PF 1989-03-16  34449964
323         Kyle Lowry        Toronto Raptors       PG 1986-03-25  33296296
397        Paul George   Los Angeles Clippers       SF 1990-05-02  33005556

In [19]:
nba.nlargest(n=5, columns=["Birthday"])

                    Name                  Team Position   Birthday   Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23  3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25   898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06  9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14  7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13   898310

In [20]:
nba.nsmallest(n=3, columns="Birthday")

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

In [21]:
nba.nsmallest(n=10, columns=["Birthday", "Salary"])

                Name                    Team Position   Birthday    Salary
98      Vince Carter           Atlanta Hawks       PF 1977-01-26   2564753
196    Udonis Haslem              Miami Heat        C 1980-06-09   2564753
262      Kyle Korver         Milwaukee Bucks       PF 1981-03-17   6004753
149   Tyson Chandler         Houston Rockets        C 1982-10-02   2564753
415   Andre Iguodala       Memphis Grizzlies       SF 1984-01-28  17185185
123  Thabo Sefolosha         Houston Rockets       PF 1984-05-02   2564753
203  Carmelo Anthony  Portland Trail Blazers       PF 1984-05-29   2159029
408     LeBron James      Los Angeles Lakers       PF 1984-12-30  37436858
58        Marc Gasol         Toronto Raptors        C 1985-01-29  25595700
32      Paul Millsap          Denver Nuggets       PF 1985-02-10  30000000

In [22]:
# applying sum() method, using numeric_only parameter set to True
nba.sum(numeric_only=True)

Salary    3444112694
dtype: int64

In [23]:
# apply the same method with parameter numeric_only with all the statistical functions
print(nba.mean(numeric_only=True),
nba.median(numeric_only=True),
nba.mode(numeric_only=True),
nba.std(numeric_only=True), sep="\n", end="")

Salary    7.653584e+06
dtype: float64
Salary    3303074.5
dtype: float64
   Salary
0   79568
Salary    9.288810e+06
dtype: float64

### SORTING
- Two types of sorting:
    - Sort by values - `sort_values()`
    - Sort by index - `sort_index()`

In [24]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [25]:
# nba.sort_values("Name")
nba.sort_values(by="Name")  # by default its ascending order

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [26]:
nba.sort_values(by="Name", ascending=False) # default value of ascending is True

                  Name                   Team Position   Birthday    Salary
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
..                 ...                    ...      ...        ...       ...
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636

[450 rows x 5 columns]

In [27]:
nba.sort_values("Birthday", ascending=False)

                    Name                  Team Position   Birthday    Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23   3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25    898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14   7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13    898310
..                   ...                   ...      ...        ...       ...
415       Andre Iguodala     Memphis Grizzlies       SF 1984-01-28  17185185
149       Tyson Chandler       Houston Rockets        C 1982-10-02   2564753
262          Kyle Korver       Milwaukee Bucks       PF 1981-03-17   6004753
196        Udonis Haslem            Miami Heat        C 1980-06-09   2564753
98          Vince Carter         Atlanta Hawks       PF 1977-01-26   2564753

[450 rows x 5 columns]

In [28]:
nba.sort_values(by=["Team", "Name"]).head(25)  # order of columns is important

                 Name            Team Position   Birthday    Salary
359          Alex Len   Atlanta Hawks        C 1993-06-16   4160000
167      Allen Crabbe   Atlanta Hawks       SG 1992-04-09  18500000
276   Brandon Goodwin   Atlanta Hawks       PG 1995-10-02     79568
438    Bruno Fernando   Atlanta Hawks        C 1998-08-15   1400000
194       Cam Reddish   Atlanta Hawks       SF 1999-09-01   4245720
111  Chandler Parsons   Atlanta Hawks       SF 1988-10-25  25102512
197     Charlie Brown   Atlanta Hawks       SG 1997-02-02     79568
130      Damian Jones   Atlanta Hawks        C 1995-06-30   2305057
213   De'Andre Hunter   Atlanta Hawks       SF 1997-12-02   7068360
28        Evan Turner   Atlanta Hawks       PG 1988-10-27  18606556
339     Jabari Parker   Atlanta Hawks       PF 1995-03-15   6500000
84       John Collins   Atlanta Hawks       PF 1997-09-23   2686560
20      Kevin Huerter   Atlanta Hawks       SG 1998-08-27   2636280
290    Tyrone Wallace   Atlanta Hawks       PG 1994-06-10   1620564
98       Vince Carter   Atlanta Hawks       PF 1977-01-26   2564753
86     Brad Wanamaker  Boston Celtics       PG 1989-07-25   1445697
340    Carsen Edwards  Boston Celtics       SG 1998-03-12   1228026
189      Daniel Theis  Boston Celtics        C 1992-04-04   5000000
419       Enes Kanter  Boston Celtics        C 1992-05-20   4767000
199    Gordon Hayward  Boston Celtics       PF 1990-03-23  32700690
118    Grant Williams  Boston Celtics       PF 1998-11-30   2379840
201     Javonte Green  Boston Celtics       SF 1993-07-23    898310
421      Jaylen Brown  Boston Celtics       SF 1996-10-24   6534829
398      Jayson Tatum  Boston Celtics       PF 1998-03-03   7830000
337      Kemba Walker  Boston Celtics       PG 1990-05-08  32742000

In [29]:
nba.sort_values(by=["Team", "Name"], ascending=False).head(25)

                      Name                Team Position   Birthday    Salary
36           Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21           Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428          Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273        Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418           Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
251              John Wall  Washington Wizards       PG 1990-09-06  38199000
127          Isaiah Thomas  Washington Wizards       PG 1989-02-07   2320044
80             Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
49             Ian Mahinmi  Washington Wizards        C 1986-11-05  15450051
283       Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
226          Davis Bertans  Washington Wizards       PF 1992-11-12   7000000
353          Chris Chiozza  Washington Wizards       PG 1995-11-21     79568
35            Bradley Beal  Washington Wizards       SG 1993-06-28  27093018
399      Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
220           Tony Bradley           Utah Jazz        C 1998-01-08   1962360
60             Rudy Gobert           Utah Jazz        C 1992-06-26  24258427
90           Royce O'Neale           Utah Jazz       PF 1993-06-05   1618520
367    Nigel Williams-Goss           Utah Jazz       PG 1994-09-16   1500000
244               Miye Oni           Utah Jazz       SG 1997-08-04    898310
345            Mike Conley           Utah Jazz       PG 1987-10-11  32511623
57            Juwan Morgan           Utah Jazz        F 1997-04-17    796806
73   Justin Wright-Foreman           Utah Jazz        G 1997-10-27     79568
66              Joe Ingles           Utah Jazz       PF 1987-10-02  11454546
232             Jeff Green           Utah Jazz       PF 1986-08-28   2564753
270       Jarrell Brantley           Utah Jazz       PF 1996-06-07     79568

In [30]:
nba.sort_values(by=["Team", "Name"], ascending=[True, False]).head(25)

                 Name            Team Position   Birthday    Salary
98       Vince Carter   Atlanta Hawks       PF 1977-01-26   2564753
290    Tyrone Wallace   Atlanta Hawks       PG 1994-06-10   1620564
20      Kevin Huerter   Atlanta Hawks       SG 1998-08-27   2636280
84       John Collins   Atlanta Hawks       PF 1997-09-23   2686560
339     Jabari Parker   Atlanta Hawks       PF 1995-03-15   6500000
28        Evan Turner   Atlanta Hawks       PG 1988-10-27  18606556
213   De'Andre Hunter   Atlanta Hawks       SF 1997-12-02   7068360
130      Damian Jones   Atlanta Hawks        C 1995-06-30   2305057
197     Charlie Brown   Atlanta Hawks       SG 1997-02-02     79568
111  Chandler Parsons   Atlanta Hawks       SF 1988-10-25  25102512
194       Cam Reddish   Atlanta Hawks       SF 1999-09-01   4245720
438    Bruno Fernando   Atlanta Hawks        C 1998-08-15   1400000
276   Brandon Goodwin   Atlanta Hawks       PG 1995-10-02     79568
167      Allen Crabbe   Atlanta Hawks       SG 1992-04-09  18500000
359          Alex Len   Atlanta Hawks        C 1993-06-16   4160000
416   Vincent Poirier  Boston Celtics        C 1993-10-17   2505793
160    Tremont Waters  Boston Celtics       PG 1998-01-10     79568
395        Tacko Fall  Boston Celtics        C 1995-12-10     79568
425      Semi Ojeleye  Boston Celtics       PF 1994-12-05   1618520
405    Romeo Langford  Boston Celtics       SG 1999-10-25   3458400
59       Marcus Smart  Boston Celtics       PG 1994-03-06  12553571
337      Kemba Walker  Boston Celtics       PG 1990-05-08  32742000
398      Jayson Tatum  Boston Celtics       PF 1998-03-03   7830000
421      Jaylen Brown  Boston Celtics       SF 1996-10-24   6534829
201     Javonte Green  Boston Celtics       SF 1993-07-23    898310

In [31]:
nba = pd.read_csv("nba.csv", parse_dates=["Birthday"], index_col="Name")
nba

C:\Users\singa\AppData\Local\Temp\ipykernel_13252\1259980527.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv", parse_dates=["Birthday"], index_col="Name")

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [32]:
nba.sort_index()

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
...                                  ...      ...        ...       ...
Zach LaVine                Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell          Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith          Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson     New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham      New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 4 columns]

In [33]:
nba.sort_index(ascending=False)

                                    Team Position   Birthday    Salary
Name
Zylan Cheatham      New Orleans Pelicans       SF 1995-11-17     79568
Zion Williamson     New Orleans Pelicans        F 2000-07-06   9757440
Zhaire Smith          Philadelphia 76ers       SG 1999-06-04   3058800
Zach Norvell          Los Angeles Lakers       SG 1997-12-09     79568
Zach LaVine                Chicago Bulls       PG 1995-03-10  19500000
...                                  ...      ...        ...       ...
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636

[450 rows x 4 columns]

In [34]:
nba.sort_index(axis=1).head(4) # OR
nba.sort_index(axis="columns").head(4)

                 Birthday Position   Salary                Team
Name
Shake Milton   1996-09-26       SG  1445697  Philadelphia 76ers
Christian Wood 1995-09-27       PF  1645357     Detroit Pistons
PJ Washington  1998-08-23       PF  3831840   Charlotte Hornets
Derrick Rose   1988-10-04       PG  7317074     Detroit Pistons

In [35]:
nba.sort_index(axis=1, ascending=False).head(4)

                              Team   Salary Position   Birthday
Name
Shake Milton    Philadelphia 76ers  1445697       SG 1996-09-26
Christian Wood     Detroit Pistons  1645357       PF 1995-09-27
PJ Washington    Charlotte Hornets  3831840       PF 1998-08-23
Derrick Rose       Detroit Pistons  7317074       PG 1988-10-04

In [36]:
nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])
nba.head()

C:\Users\singa\AppData\Local\Temp\ipykernel_13252\3192490490.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

### SETTING NEW INDEX

In [37]:
nba.set_index(keys="Name")
nba.set_index("Name")

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [38]:
nba = nba.set_index("Name")
nba.head(3)

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840

### SELECTING ROWS AND COLUMNS

In [39]:
nba["Team"]

Name
Shake Milton       Philadelphia 76ers
Christian Wood        Detroit Pistons
PJ Washington       Charlotte Hornets
Derrick Rose          Detroit Pistons
Marial Shayok      Philadelphia 76ers
                         ...
Austin Rivers         Houston Rockets
Harry Giles          Sacramento Kings
Robin Lopez           Milwaukee Bucks
Collin Sexton     Cleveland Cavaliers
Ricky Rubio              Phoenix Suns
Name: Team, Length: 450, dtype: object

In [40]:
nba[["Team", "Salary"]].head(3)

                              Team   Salary
Name
Shake Milton    Philadelphia 76ers  1445697
Christian Wood     Detroit Pistons  1645357
PJ Washington    Charlotte Hornets  3831840

In [41]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 450 entries, Shake Milton to Ricky Rubio
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Team      450 non-null    object
 1   Position  450 non-null    object
 2   Birthday  450 non-null    datetime64[ns]
 3   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 33.7+ KB

In [42]:
nba.select_dtypes(include="object").head(3)  # selecting columns of specific data types

                              Team Position
Name
Shake Milton    Philadelphia 76ers       SG
Christian Wood     Detroit Pistons       PF
PJ Washington    Charlotte Hornets       PF

In [43]:
nba.select_dtypes(exclude=["object", "int"]).head(3)   # exclude coluns of a specific datatype(s)

                 Birthday
Name
Shake Milton   1996-09-26
Christian Wood 1995-09-27
PJ Washington  1998-08-23

#### loc[] - loc stands for location

In [44]:
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [45]:
nba.loc["PJ Washington"]

Team          Charlotte Hornets
Position                     PF
Birthday    1998-08-23 00:00:00
Salary                  3831840
Name: PJ Washington, dtype: object

In [46]:
nba.loc["Christian Wood":"Derrick Rose"] # the end is inclusive

                             Team Position   Birthday   Salary
Name
Christian Wood    Detroit Pistons       PF 1995-09-27  1645357
PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose      Detroit Pistons       PG 1988-10-04  7317074

In [47]:
nba.loc[["Christian Wood", "Harry Giles", "Ricky Rubio"]]

                            Team Position   Birthday    Salary
Name
Christian Wood   Detroit Pistons       PF 1995-09-27   1645357
Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

In [48]:
nba.loc["Harry Giles":]

                              Team Position   Birthday    Salary
Name
Harry Giles       Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez        Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio           Phoenix Suns       PG 1990-10-21  16200000

In [49]:
nba.loc[:"Christian Wood"]

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [50]:
nba.loc["Harry Giles":"Ricky Rubio", ["Birthday", "Salary"]]

                Birthday    Salary
Name
Harry Giles   1998-04-22   2578800
Robin Lopez   1988-04-01   4767000
Collin Sexton 1999-01-04   4764960
Ricky Rubio   1990-10-21  16200000

#### iloc[ ] - i loc stands integer location

In [51]:
nba.iloc[0:3]   # 3 is exclusive

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840

In [52]:
nba.iloc[0:20:3]

                                Team Position   Birthday   Salary
Name
Shake Milton      Philadelphia 76ers       SG 1996-09-26  1445697
Derrick Rose         Detroit Pistons       PG 1988-10-04  7317074
Kendrick Nunn             Miami Heat       SG 1995-08-03  1416852
Torrey Craig          Denver Nuggets       SF 1990-12-19  2000000
Norvel Pelle      Philadelphia 76ers       FC 1993-02-03    79568
JaMychal Green  Los Angeles Clippers       PF 1990-06-21  4767000
Chris Boucher        Toronto Raptors       PF 1993-01-11  1588231

In [53]:
nba.iloc[0:3, 0:2]

                              Team Position
Name
Shake Milton    Philadelphia 76ers       SG
Christian Wood     Detroit Pistons       PF
PJ Washington    Charlotte Hornets       PF

### RENAMING THE COLUMNS

In [54]:
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [55]:
nba.rename(columns={"Birthday":"Date of Birth", "Salary":"Pay"})

                               Team Position Date of Birth       Pay
Name
Shake Milton     Philadelphia 76ers       SG    1996-09-26   1445697
Christian Wood      Detroit Pistons       PF    1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF    1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG    1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G    1995-07-26     79568
...                             ...      ...           ...       ...
Austin Rivers       Houston Rockets       PG    1992-08-01   2174310
Harry Giles        Sacramento Kings       PF    1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C    1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG    1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG    1990-10-21  16200000

[450 rows x 4 columns]

In [56]:
nba = nba.rename(columns={"Birthday":"Date of Birth", "Salary":"Pay"})
nba

                               Team Position Date of Birth       Pay
Name
Shake Milton     Philadelphia 76ers       SG    1996-09-26   1445697
Christian Wood      Detroit Pistons       PF    1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF    1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG    1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G    1995-07-26     79568
...                             ...      ...           ...       ...
Austin Rivers       Houston Rockets       PG    1992-08-01   2174310
Harry Giles        Sacramento Kings       PF    1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C    1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG    1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG    1990-10-21  16200000

[450 rows x 4 columns]

In [57]:
nba = nba.rename(columns={"Date of Birth":"Birthday"})
nba.head(3)

                              Team Position   Birthday      Pay
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840

In [59]:
nba = nba.rename(index={"Shake Milton":"Stable Milton"})
nba.head(3)

                              Team Position   Birthday      Pay
Name
Stable Milton   Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840

In [64]:
nba.reset_index().set_index("Team").head(3)

                              Name Position   Birthday      Pay
Team
Philadelphia 76ers   Stable Milton       SG 1996-09-26  1445697
Detroit Pistons     Christian Wood       PF 1995-09-27  1645357
Charlotte Hornets    PJ Washington       PF 1998-08-23  3831840

In [63]:
nba.reset_index().set_index("Name")

                               Team Position   Birthday       Pay
Name
Stable Milton    Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

## FILTERING A DATAFRAME

In [65]:
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"])
employees.head(3)

C:\Users\singa\AppData\Local\Temp\ipykernel_13252\793836341.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv("employees.csv", parse_dates=["Start Date"])

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance

In [66]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.0+ KB

#### `astype()` method to convert data types

In [67]:
employees["Mgmt"] = employees["Mgmt"].astype(bool)
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [69]:
# employees["Salary"] = employees["Salary"].astype(int) # IntCastingNaNError - integer type

In [72]:
employees.head(3)

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance

In [73]:
# use fillna(value) method to to replace NaN values to specified value

In [74]:
employees["Salary"].fillna(0)

0            0.0
1        61933.0
2       130590.0
3       138705.0
4       101004.0
          ...
996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         0.0
Name: Salary, Length: 1001, dtype: float64

employees.Salary

In [77]:
employees["Salary"] = employees["Salary"].fillna(0).astype(int)

In [78]:
employees.head(3)

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance

In [79]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int32(1), object(3)
memory usage: 36.3+ KB

In [80]:
len(employees)

1001

In [81]:
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [82]:
employees["Gender"] = employees["Gender"].astype("category")
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int32(1), object(2)
memory usage: 29.6+ KB

In [83]:
employees["Team"] = employees["Team"].astype("category")
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int32
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int32(1), object(1)
memory usage: 23.1+ KB

#### Conditions to apply for filtering

In [84]:
employees.head(10)

  First Name  Gender Start Date  Salary   Mgmt          Team
0    Douglas    Male 1993-08-06       0   True     Marketing
1     Thomas    Male 1996-03-31   61933   True           NaN
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
6       Ruby  Female 1987-08-17   65476   True       Product
7        NaN  Female 2015-07-20   45906   True       Finance
8     Angela  Female 2005-11-22   95570   True   Engineering
9    Frances  Female 2002-08-08  139852   True  Business Dev

In [88]:
# a condition to create a boolean Series
employees["First Name"] == "Maria"

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [89]:
# which can be used to filter the rows
marias = employees["First Name"] == "Maria"
# filter the dataframe with the condition
employees[marias]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [90]:
"Finance" != "Engineering"

True

In [92]:
employees[employees["Team"] == "Finance"]

    First Name  Gender Start Date  Salary   Mgmt     Team
2        Maria  Female        NaT  130590  False  Finance
3        Jerry     NaN 2005-03-04  138705   True  Finance
7          NaN  Female 2015-07-20   45906   True  Finance
14    Kimberly  Female 1999-01-14   41426   True  Finance
46       Bruce    Male 2009-11-28  114796  False  Finance
..         ...     ...        ...     ...    ...      ...
907  Elizabeth  Female 1998-07-27  137144  False  Finance
954        Joe    Male 1980-01-19  119667   True  Finance
987     Gloria  Female 2014-12-08  136709   True  Finance
992    Anthony    Male 2011-10-16  112769   True  Finance
996    Phillip    Male 1984-01-31   42392  False  Finance

[102 rows x 6 columns]

In [93]:
finance = employees["Team"] == "Finance"
employees[finance]

    First Name  Gender Start Date  Salary   Mgmt     Team
2        Maria  Female        NaT  130590  False  Finance
3        Jerry     NaN 2005-03-04  138705   True  Finance
7          NaN  Female 2015-07-20   45906   True  Finance
14    Kimberly  Female 1999-01-14   41426   True  Finance
46       Bruce    Male 2009-11-28  114796  False  Finance
..         ...     ...        ...     ...    ...      ...
907  Elizabeth  Female 1998-07-27  137144  False  Finance
954        Joe    Male 1980-01-19  119667   True  Finance
987     Gloria  Female 2014-12-08  136709   True  Finance
992    Anthony    Male 2011-10-16  112769   True  Finance
996    Phillip    Male 1984-01-31   42392  False  Finance

[102 rows x 6 columns]

In [94]:
# employees[employees["Salary"] > 100000] # OR
high_salaries = employees["Salary"] > 100000
employees[high_salaries]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
3        Jerry     NaN 2005-03-04  138705   True       Finance
4        Larry    Male 1998-01-24  101004   True            IT
5       Dennis    Male 1987-04-18  115163  False         Legal
9      Frances  Female 2002-08-08  139852   True  Business Dev
..         ...     ...        ...     ...    ...           ...
990      Robin  Female 1987-07-24  100765   True            IT
991       Rose  Female 2002-08-25  134505   True     Marketing
992    Anthony    Male 2011-10-16  112769   True       Finance
995      Henry     NaN 2014-11-23  132483  False  Distribution
999     Albert    Male 2012-05-15  129949   True         Sales

[409 rows x 6 columns]

In [95]:
is_female = employees["Gender"] == "Female"
is_biz_dev = employees["Team"] == "Business Dev"
# combine the two filter using & (and) - both the conditions must be met
employees[is_female & is_biz_dev]

    First Name  Gender Start Date  Salary   Mgmt          Team
9      Frances  Female 2002-08-08  139852   True  Business Dev
33        Jean  Female 1993-12-18  119082  False  Business Dev
36      Rachel  Female 2009-02-16  142032  False  Business Dev
38   Stephanie  Female 1986-09-13   36844   True  Business Dev
61      Denise  Female 2001-11-06  106862  False  Business Dev
66       Nancy  Female 2012-12-15  125250   True  Business Dev
92       Linda  Female 2000-05-25  119009   True  Business Dev
111     Bonnie  Female 1999-12-17   42153   True  Business Dev
114     Ashley  Female 2002-08-04   58698   True  Business Dev
118     Andrea  Female 2012-01-12  120204  False  Business Dev
134    Carolyn  Female 2011-04-09  109260   True  Business Dev
155      Marie  Female 2003-03-16  104058   True  Business Dev
164       Mary  Female 1999-08-13  134645  False  Business Dev
182    Lillian  Female 1999-06-19  123940   True  Business Dev
203      Diana  Female 2013-01-04  103521   True  Business Dev
249      Betty  Female 2002-06-12  104896   True  Business Dev
275      Debra  Female 1994-02-22  104250   True  Business Dev
279       Ruby  Female 2000-11-08  105946  False  Business Dev
317      Kathy  Female 2013-12-18  132381  False  Business Dev
324       Ruby  Female 1988-12-10   76707  False  Business Dev
368    Marilyn  Female 1982-12-17  147183  False  Business Dev
370      Linda  Female 2009-07-15  144001  False  Business Dev
401      Norma  Female 1996-04-16   38872   True  Business Dev
406       Mary  Female 2010-08-22   42214   True  Business Dev
419    Dorothy  Female 2013-11-05  140136   True  Business Dev
441     Louise  Female 2003-05-13   46666   True  Business Dev
481        NaN  Female 2013-04-27   93847   True  Business Dev
487     Cheryl  Female 2014-12-03   71751  False  Business Dev
498      Diana  Female 1994-06-13   41831  False  Business Dev
509        Ann  Female 1984-11-04   90719  False  Business Dev
537    Cynthia  Female 1991-09-14   51633   True  Business Dev
583      Diane  Female 1988-02-02   49501  False  Business Dev
590     Andrea  Female 1994-10-30   87575   True  Business Dev
638    Frances  Female 1996-11-12  112467  False  Business Dev
735    Barbara  Female 2002-11-26   82884   True  Business Dev
746     Gloria  Female 2004-08-19   46602   True  Business Dev
748     Martha  Female 1997-07-17   94963   True  Business Dev
772    Lillian  Female 2009-08-14  113554   True  Business Dev
779      Doris  Female 1984-09-08  114360   True  Business Dev
802       Jane  Female 1992-01-12   51923  False  Business Dev
822    Deborah  Female 2009-02-26  118043   True  Business Dev
841       Ruby  Female 2006-08-13   48354  False  Business Dev
852      Diana  Female 2004-11-19  105066   True  Business Dev
859      Robin  Female 2012-10-01   41808  False  Business Dev
872     Brenda  Female 2015-01-18   73749  False  Business Dev
898       Jane  Female 2012-04-27   59680   True  Business Dev
916    Marilyn  Female 1996-01-16  118369   True  Business Dev
933      Doris  Female 1993-07-05  141439  False  Business Dev
936      Maria  Female 2003-03-14   96250  False  Business Dev
950      Paula  Female 1983-05-21   58423  False  Business Dev

In [96]:
# Mgmt column is a boolean column, we can directly use it to filter the data
is_manager = employees["Mgmt"]
employees[is_manager]

     First Name  Gender Start Date  Salary  Mgmt         Team
0       Douglas    Male 1993-08-06       0  True    Marketing
1        Thomas    Male 1996-03-31   61933  True          NaN
3         Jerry     NaN 2005-03-04  138705  True      Finance
4         Larry    Male 1998-01-24  101004  True           IT
6          Ruby  Female 1987-08-17   65476  True      Product
...         ...     ...        ...     ...   ...          ...
992     Anthony    Male 2011-10-16  112769  True      Finance
993        Tina  Female 1997-05-15   56450  True  Engineering
994      George    Male 2013-06-21   98874  True    Marketing
999      Albert    Male 2012-05-15  129949  True        Sales
1000        NaN     NaN        NaT       0  True          NaN

[536 rows x 6 columns]

In [97]:
# Inversion operator - ~
# Inverts True to False, and False to True

In [98]:
employees[~is_manager]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
5       Dennis    Male 1987-04-18  115163  False         Legal
13        Gary    Male 2008-01-27  109831  False         Sales
15     Lillian  Female 2016-06-05   59414  False       Product
16      Jeremy    Male 2010-09-21   90370  False            HR
..         ...     ...        ...     ...    ...           ...
989     Justin     NaN 1991-02-10   38344  False         Legal
995      Henry     NaN 2014-11-23  132483  False  Distribution
996    Phillip    Male 1984-01-31   42392  False       Finance
997    Russell    Male 2013-05-20   96914  False       Product
998      Larry    Male 2013-04-20   60500  False  Business Dev

[465 rows x 6 columns]

In [100]:
employees[~(employees["Salary"] > 100000)]

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
6          Ruby  Female 1987-08-17   65476   True       Product
7           NaN  Female 2015-07-20   45906   True       Finance
8        Angela  Female 2005-11-22   95570   True   Engineering
...         ...     ...        ...     ...    ...           ...
994      George    Male 2013-06-21   98874   True     Marketing
996     Phillip    Male 1984-01-31   42392  False       Finance
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
1000        NaN     NaN        NaT       0   True           NaN

[592 rows x 6 columns]

In [106]:
# The or operator is |
sales = employees["Team"] == "Sales"
marketing = employees["Team"] == "Marketing"
legal = employees["Team"] == "Legal"
employees[sales | marketing | legal]

    First Name  Gender Start Date  Salary   Mgmt       Team
0      Douglas    Male 1993-08-06       0   True  Marketing
5       Dennis    Male 1987-04-18  115163  False      Legal
11       Julie  Female 1997-10-26  102508   True      Legal
13        Gary    Male 2008-01-27  109831  False      Sales
20        Lois     NaN 1995-04-22   64714   True      Legal
..         ...     ...        ...     ...    ...        ...
986      Donna  Female 1982-11-26   82871  False  Marketing
989     Justin     NaN 1991-02-10   38344  False      Legal
991       Rose  Female 2002-08-25  134505   True  Marketing
994     George    Male 2013-06-21   98874   True  Marketing
999     Albert    Male 2012-05-15  129949   True      Sales

[280 rows x 6 columns]

In [104]:
# isin() method instead of '|' opeators
star_teams = ["Sales", "Marketing", "Legal"]
all_star_teams = employees["Team"].isin(star_teams)
employees[all_star_teams]

    First Name  Gender Start Date  Salary   Mgmt       Team
0      Douglas    Male 1993-08-06       0   True  Marketing
5       Dennis    Male 1987-04-18  115163  False      Legal
11       Julie  Female 1997-10-26  102508   True      Legal
13        Gary    Male 2008-01-27  109831  False      Sales
20        Lois     NaN 1995-04-22   64714   True      Legal
..         ...     ...        ...     ...    ...        ...
986      Donna  Female 1982-11-26   82871  False  Marketing
989     Justin     NaN 1991-02-10   38344  False      Legal
991       Rose  Female 2002-08-25  134505   True  Marketing
994     George    Male 2013-06-21   98874   True  Marketing
999     Albert    Male 2012-05-15  129949   True      Sales

[280 rows x 6 columns]

```
pip install library_name
pip install library_name==version_num
pip install pandas==3.0.4
```

In [109]:
higher_than_80k = employees["Salary"] >= 80000
lower_than_100k = employees["Salary"] <= 100000
employees[higher_than_80k & lower_than_100k]

    First Name  Gender Start Date  Salary   Mgmt         Team
8       Angela  Female 2005-11-22   95570   True  Engineering
16      Jeremy    Male 2010-09-21   90370  False           HR
19       Donna  Female 2010-07-22   81014  False      Product
22      Joshua     NaN 2012-03-08   90816   True           IT
24        John    Male 1992-07-01   97950  False           IT
..         ...     ...        ...     ...    ...          ...
982       Rose  Female 1982-04-06   91411   True           HR
985    Stephen     NaN 1983-07-10   85668  False        Legal
986      Donna  Female 1982-11-26   82871  False    Marketing
994     George    Male 2013-06-21   98874   True    Marketing
997    Russell    Male 2013-05-20   96914  False      Product

[188 rows x 6 columns]

In [110]:
# use between() method for numeric and date columns
salary_80_100k = employees["Salary"].between(80000, 100000)
employees[salary_80_100k]

    First Name  Gender Start Date  Salary   Mgmt         Team
8       Angela  Female 2005-11-22   95570   True  Engineering
16      Jeremy    Male 2010-09-21   90370  False           HR
19       Donna  Female 2010-07-22   81014  False      Product
22      Joshua     NaN 2012-03-08   90816   True           IT
24        John    Male 1992-07-01   97950  False           IT
..         ...     ...        ...     ...    ...          ...
982       Rose  Female 1982-04-06   91411   True           HR
985    Stephen     NaN 1983-07-10   85668  False        Legal
986      Donna  Female 1982-11-26   82871  False    Marketing
994     George    Male 2013-06-21   98874   True    Marketing
997    Russell    Male 2013-05-20   96914  False      Product

[188 rows x 6 columns]

In [111]:
# use the between() with dates
folkes_80k = employees["Start Date"].between(
    left="1980-01-01",
    right="1990-01-01"
)
employees[folkes_80k]

    First Name  Gender Start Date  Salary   Mgmt         Team
5       Dennis    Male 1987-04-18  115163  False        Legal
6         Ruby  Female 1987-08-17   65476   True      Product
10      Louise  Female 1980-08-12   63241   True          NaN
12     Brandon    Male 1980-12-01  112807   True           HR
17       Shawn    Male 1986-12-07  111737  False      Product
..         ...     ...        ...     ...    ...          ...
983       John    Male 1982-12-23  146907  False  Engineering
985    Stephen     NaN 1983-07-10   85668  False        Legal
986      Donna  Female 1982-11-26   82871  False    Marketing
990      Robin  Female 1987-07-24  100765   True           IT
996    Phillip    Male 1984-01-31   42392  False      Finance

[240 rows x 6 columns]